[package]
name = "init_data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
rusqlite = { version = "*", features = ["bundled"] }
log = "*"
pretty_env_logger = "*"